# Generated by Django 5.0.3 on 2024-03-26 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=250, verbose_name='Song Name')),
                ('song_author', models.CharField(max_length=250, verbose_name='Song Author')),
                ('favorite_song', models.CharField(default=0, max_length=10, verbose_name='Favorite song')),
                ('song_img', models.ImageField(default='default.jpg', upload_to='song_img/', verbose_name='Song Image')),
                ('song_file', models.FileField(upload_to='songs/', verbose_name='Song File')),
                ('song_listen_count', models.IntegerField(default=0, verbose_name='Song Listen Count')),
                ('song_add_date', models.DateTimeField(auto_now_add=True, verbose_name='Song Added Date')),
            ],
            options={
                'verbose_name': 'Songs',
                'db_table': 'songs',
                'ordering': ['-song_add_date'],
            },
        ),
    ]
