# Generated by Django 5.0.3 on 2024-03-31 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='song_description',
            field=models.TextField(default=1, verbose_name='Song Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='songs',
            name='favorite_song',
            field=models.BooleanField(default=False, verbose_name='Favourite Songs'),
        ),
    ]
