# Generated by Django 5.0.3 on 2024-03-31 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0002_songs_song_description_alter_songs_favorite_song'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='songs',
            options={'ordering': ['-song_add_date'], 'verbose_name': 'Song', 'verbose_name_plural': 'Songs'},
        ),
    ]
